// <auto-generated />
using System;
using Cine.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cine.Api.Migrations
{
    [DbContext(typeof(CineContext))]
    partial class CineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cine.Api.Models.Entities.Pelicula", b =>
                {
                    b.Property<int>("PeliculaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pelicula");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeliculaId"));

                    b.Property<DateTime?>("AuditDeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("audit_delete_date");

                    b.Property<int?>("AuditDeleteUser")
                        .HasColumnType("int")
                        .HasColumnName("audit_delete_user");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duracion");

                    b.HasKey("PeliculaId");

                    b.ToTable("pelicula", (string)null);
                });

            modelBuilder.Entity("Cine.Api.Models.Entities.PeliculaSalacine", b =>
                {
                    b.Property<int>("PeliculaSalaCineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeliculaSalaCineId"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_publicacion");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("int")
                        .HasColumnName("peliculaId");

                    b.Property<int>("SalaCineId")
                        .HasColumnType("int")
                        .HasColumnName("salaCineId");

                    b.HasKey("PeliculaSalaCineId");

                    b.HasIndex("PeliculaId");

                    b.HasIndex("SalaCineId");

                    b.ToTable("pelicula_salacine", (string)null);
                });

            modelBuilder.Entity("Cine.Api.Models.Entities.SalaCine", b =>
                {
                    b.Property<int>("SalaCineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaCineId"));

                    b.Property<DateTime?>("AuditDeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("audit_delete_date");

                    b.Property<int?>("AuditDeleteUser")
                        .HasColumnType("int")
                        .HasColumnName("audit_delete_user");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("SalaCineId");

                    b.ToTable("sala_cine", (string)null);
                });

            modelBuilder.Entity("Cine.Api.Models.Entities.PeliculaSalacine", b =>
                {
                    b.HasOne("Cine.Api.Models.Entities.Pelicula", "Pelicula")
                        .WithMany("PeliculaSalacines")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cine.Api.Models.Entities.SalaCine", "SalaCine")
                        .WithMany("PeliculaSalacines")
                        .HasForeignKey("SalaCineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelicula");

                    b.Navigation("SalaCine");
                });

            modelBuilder.Entity("Cine.Api.Models.Entities.Pelicula", b =>
                {
                    b.Navigation("PeliculaSalacines");
                });

            modelBuilder.Entity("Cine.Api.Models.Entities.SalaCine", b =>
                {
                    b.Navigation("PeliculaSalacines");
                });
#pragma warning restore 612, 618
        }
    }
}
